api:
  usgs:
    base_url: "https://earthquake.usgs.gov/fdsnws/event/1"
    timeout: 30s
    rate_limit: 60
  emsc:
    base_url: "https://www.emsc-csem.org/javascript"
    timeout: 30s

storage:
  output_dir: "./data"
  earthquakes_dir: "earthquakes"
  faults_dir: "faults"

logging:
  level: "info"
  format: "json"
  output: "stdout"

collection:
  default_limit: 1000
  max_limit: 10000
  retry_attempts: 3
  retry_delay: 5s 