api:
    emsc:
        base_url: https://www.emsc-csem.org/javascript
        timeout: 30s
    usgs:
        base_url: https://earthquake.usgs.gov/fdsnws/event/1
        rate_limit: 60
        timeout: 30s
collection:
    default_limit: 1000
    max_limit: 10000
    retry_attempts: 3
    retry_delay: 5s
database:
    connection_timeout: 30s
    database: quakewatch
    enabled: false
    host: localhost
    max_connections: 10
    password: ""
    port: 5432
    ssl_mode: disable
    type: postgres
    username: postgres
logging:
    format: json
    level: info
    output: stdout
storage:
    earthquakes_dir: earthquakes
    faults_dir: faults
    output_dir: ./data
