name: Test and Build

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

env:
  GO_VERSION: '1.24'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        working-directory: apps/scraper
        run: |
          go mod download
          go mod tidy

      - name: Run tests
        working-directory: apps/scraper
        run: go test -v ./...

      - name: Run linter
        working-directory: apps/scraper
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.57.2
          golangci-lint run

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build for current platform
        working-directory: apps/scraper
        run: |
          go build -o bin/quakewatch-scraper cmd/scraper/main.go

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: quakewatch-scraper
          path: apps/scraper/bin/quakewatch-scraper 